# Generated by Django 5.2.12 on 2026-03-26 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_key', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image_url', models.URLField(blank=True, default='', max_length=1024)),
                ('link_url', models.URLField(blank=True, default='', max_length=1024)),
                ('is_active', models.BooleanField(default=True)),
                ('placement', models.CharField(choices=[('feed', 'Feed'), ('sidebar', 'Sidebar'), ('banner', 'Banner')], default='feed', max_length=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('media_url', models.URLField(blank=True, default='', max_length=1024)),
                ('media_type', models.CharField(blank=True, choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document')], default='', max_length=10)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('collected_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='CharityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=255)),
                ('donor_email', models.EmailField(max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('donation_type', models.CharField(choices=[('charity', 'Charity'), ('sponsor_fund', 'Sponsor Fund'), ('campaign', 'Campaign')], max_length=20)),
                ('charity_type', models.CharField(blank=True, default='', max_length=100)),
                ('fund_type', models.CharField(blank=True, default='', max_length=100)),
                ('campaign_id', models.CharField(blank=True, default='', max_length=50)),
                ('is_public', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('account_number', models.CharField(blank=True, default='', max_length=50)),
                ('bank_title', models.CharField(blank=True, default='', max_length=255)),
                ('transaction_screenshot', models.URLField(blank=True, default='', max_length=1024)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='FundType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LiveBroadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('broadcaster_name', models.CharField(max_length=255)),
                ('broadcaster_email', models.EmailField(max_length=254)),
                ('stream_url', models.URLField(blank=True, default='', max_length=1024)),
                ('thumbnail_url', models.URLField(blank=True, default='', max_length=1024)),
                ('is_live', models.BooleanField(default=False)),
                ('viewers_count', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('total_votes', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('media_url', models.URLField(blank=True, default='', max_length=1024)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('none', 'None')], default='none', max_length=10)),
                ('author_name', models.CharField(max_length=255)),
                ('author_email', models.EmailField(max_length=254)),
                ('likes_count', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('survey_type', models.CharField(choices=[('household', 'Household'), ('infrastructure', 'Infrastructure'), ('health', 'Health'), ('education', 'Education'), ('general', 'General')], default='general', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed')], default='draft', max_length=10)),
                ('questions', models.JSONField(blank=True, default=list, null=True)),
                ('created_by', models.EmailField(blank=True, default='', max_length=254)),
                ('created_by_name', models.CharField(blank=True, default='', max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('team_type', models.CharField(choices=[('zakat_collection', 'Zakat Collection'), ('needy_support', 'Needy Support'), ('survey', 'Survey'), ('general', 'General')], default='general', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('created_by_name', models.CharField(blank=True, default='', max_length=255)),
                ('member_emails', models.JSONField(blank=True, default=list, null=True)),
                ('cover_image_url', models.URLField(blank=True, default='', max_length=1024)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=255)),
                ('votes_count', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='posts.poll')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('author_name', models.CharField(max_length=255)),
                ('author_email', models.EmailField(max_length=254)),
                ('media_url', models.URLField(blank=True, default='', max_length=1024)),
                ('media_type', models.CharField(choices=[('none', 'None'), ('image', 'Image'), ('video', 'Video'), ('gif', 'GIF'), ('sticker', 'Sticker')], default='none', max_length=10)),
                ('voice_note_url', models.URLField(blank=True, default='', max_length=1024)),
                ('mentioned_users', models.JSONField(blank=True, default=list, null=True)),
                ('reactions', models.JSONField(blank=True, default=dict, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='posts.comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.post')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_email', models.EmailField(max_length=254)),
                ('reporter_name', models.CharField(blank=True, default='', max_length=255)),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('hate_speech', 'Hate Speech'), ('violence', 'Violence'), ('misinformation', 'Misinformation'), ('nudity', 'Nudity'), ('other', 'Other')], max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('dismissed', 'Dismissed')], default='pending', max_length=10)),
                ('post_author_email', models.EmailField(blank=True, default='', max_length=254)),
                ('post_content_preview', models.CharField(blank=True, default='', max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='posts.post')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respondent_name', models.CharField(max_length=255)),
                ('respondent_address', models.CharField(blank=True, default='', max_length=500)),
                ('answers', models.JSONField(blank=True, default=list, null=True)),
                ('submitted_by', models.EmailField(blank=True, default='', max_length=254)),
                ('submitted_by_name', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='posts.survey')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to='posts.team')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.AddField(
            model_name='survey',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='posts.team'),
        ),
        migrations.CreateModel(
            name='NeedyPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, default='', max_length=500)),
                ('contact_number', models.CharField(blank=True, default='', max_length=20)),
                ('family_size', models.IntegerField(blank=True, null=True)),
                ('need_type', models.CharField(choices=[('food', 'Food'), ('medical', 'Medical'), ('education', 'Education'), ('financial', 'Financial'), ('housing', 'Housing'), ('other', 'Other')], max_length=20)),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('assisted', 'Assisted'), ('resolved', 'Resolved')], default='active', max_length=10)),
                ('added_by', models.EmailField(blank=True, default='', max_length=254)),
                ('added_by_name', models.CharField(blank=True, default='', max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='needy_persons', to='posts.team')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_email', models.EmailField(max_length=254)),
                ('member_name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('leader', 'Leader'), ('member', 'Member')], default='member', max_length=10)),
                ('joined_date', models.DateField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='posts.team')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='ZakatCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collector_name', models.CharField(max_length=255)),
                ('collector_email', models.EmailField(blank=True, default='', max_length=254)),
                ('donor_name', models.CharField(max_length=255)),
                ('donor_address', models.CharField(blank=True, default='', max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('collection_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('collected', 'Collected'), ('pending', 'Pending'), ('distributed', 'Distributed')], default='collected', max_length=15)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zakat_collections', to='posts.team')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='PollVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_email', models.EmailField(max_length=254)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_records', to='posts.polloption')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='posts.poll')),
            ],
            options={
                'unique_together': {('poll', 'voter_email')},
            },
        ),
    ]
