# Generated by Django 5.2.12 on 2026-03-27 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_post_of_the_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('only_me', 'Only Me'), ('friends', 'Friends'), ('public', 'Public')], default='public', max_length=10),
        ),
    ]
