# Generated by Django 5.2.12 on 2026-04-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_personality_villagehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='media_items',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
